Repository Bithumb-Tech-Camp/Bithumb-Project, pull requests merged in 2022-03, with the labels that each got.

#15 feat : HTTPManager, WebSockerManager Request 메서드 수정
  BithumbProject/BithumbProject.xcodeproj/project.pbxproj
  BithumbProject/BithumbProject.xcodeproj/xcshareddata/xcschemes/BithumbProject.xcscheme
  BithumbProject/BithumbProject/Sources/Models/OrderBook.swift
  BithumbProject/BithumbProject/Sources/Models/TransactionHistory.swift
  BithumbProject/BithumbProject/Sources/Repositories/HTTPManager.swift
  BithumbProject/BithumbProject/Sources/Repositories/WebSocketManager.swift
  BithumbProject/BithumbProject/Sources/Views/OrderBookCell.swift
  BithumbProject/BithumbProject/Sources/Views/OrderBookViewController.swift
  BithumbProject/Podfile
  BithumbProject/Podfile.lock
Labels: feat

#16 feat: CoinDetailViewController 구현
  BithumbProject/BithumbProject.xcodeproj/project.pbxproj
  BithumbProject/BithumbProject/Sources/Models/RealtimeTicker.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Extensions/Double+Extension.swift
  BithumbProject/BithumbProject/Sources/ViewModels/CoinDetailViewModel.swift
  BithumbProject/BithumbProject/Sources/Views/ChartViewController.swift
  BithumbProject/BithumbProject/Sources/Views/CoinDetailButtonBarPagerViewController.swift
  BithumbProject/BithumbProject/Sources/Views/CoinDetailViewController.swift
Labels: feat

#19 MainUI 구현 및 정렬 기능 초기 세팅
  BithumbProject/BithumbProject.xcodeproj/project.pbxproj
  BithumbProject/BithumbProject/Sources/Application/CoinListService.swift
  BithumbProject/BithumbProject/Sources/Application/SceneDelegate.swift
  BithumbProject/BithumbProject/Sources/Models/ChangeRate.swift
  BithumbProject/BithumbProject/Sources/Models/ChangeRatePeriod.swift
  BithumbProject/BithumbProject/Sources/Models/Coin.swift
  BithumbProject/BithumbProject/Sources/Models/CoinListType.swift
  BithumbProject/BithumbProject/Sources/Models/SortedColumn.swift
  BithumbProject/BithumbProject/Sources/Models/Ticker.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Constants/Constant.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Extensions/UINavigationBar+Extension.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Extensions/UIVIewController+Extension.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Protocols/ViewModelType.swift
  BithumbProject/BithumbProject/Sources/ViewModels/CoinListViewModel.swift
  BithumbProject/BithumbProject/Sources/Views/ButtonBarCell.swift
  BithumbProject/BithumbProject/Sources/Views/ButtonBarCollectionView.swift
  BithumbProject/BithumbProject/Sources/Views/ButtonBarController.swift
  BithumbProject/BithumbProject/Sources/Views/ChangeRateCell.swift
  BithumbProject/BithumbProject/Sources/Views/ChangeRateSettingHeaderView.swift
  BithumbProject/BithumbProject/Sources/Views/ChangeRateSettingViewController.swift
  BithumbProject/BithumbProject/Sources/Views/CoinCell.swift
  BithumbProject/BithumbProject/Sources/Views/CoinDetailViewController.swift
  BithumbProject/BithumbProject/Sources/Views/CoinListButtonBarPagerViewController.swift
  BithumbProject/BithumbProject/Sources/Views/CoinListViewController.swift
  BithumbProject/BithumbProject/Sources/Views/FavoriteCoinViewController.swift
  BithumbProject/BithumbProject/Sources/Views/KRWViewController.swift
  BithumbProject/BithumbProject/Sources/Views/PeriodCell.swift
  BithumbProject/BithumbProject/Sources/Views/PopularityViewController.swift
  BithumbProject/BithumbProject/Sources/Views/StarButton.swift
  BithumbProject/BithumbProject/Sources/Views/StarCell.swift
  BithumbProject/BithumbProject/Sources/Views/TickerCell.swift
  BithumbProject/BithumbProject/Sources/Views/TitleCell.swift
  BithumbProject/BithumbProject/Sources/Views/TransactionCell.swift
Labels: enhancement, feat

#22 refactor: paul 코드 변경 사항 반영
  BithumbProject/BithumbProject.xcodeproj/project.pbxproj
  BithumbProject/BithumbProject/Sources/ViewModels/ChartViewModel.swift
  BithumbProject/BithumbProject/Sources/ViewModels/CoinDetailViewModel.swift
  BithumbProject/BithumbProject/Sources/Views/ChartViewController.swift
  BithumbProject/BithumbProject/Sources/Views/CoinDetailButtonBarPagerViewController.swift
  BithumbProject/BithumbProject/Sources/Views/CoinListViewController.swift
Labels: refactor

#23 feat : OrderBookViewController, TransactionViewController 구현
  BithumbProject/BithumbProject.xcodeproj/project.pbxproj
  BithumbProject/BithumbProject/Sources/Application/SceneDelegate.swift
  BithumbProject/BithumbProject/Sources/Models/TransactionHistory.swift
  BithumbProject/BithumbProject/Sources/Repositories/HTTPService.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Constants/Constant.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Extensions/Color+Extension.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Extensions/String+Extension.swift
  BithumbProject/BithumbProject/Sources/ViewModels/OrderBookViewModel.swift
  BithumbProject/BithumbProject/Sources/ViewModels/TransactionViewModel.swift
  BithumbProject/BithumbProject/Sources/Views/OrderBookCell.swift
  BithumbProject/BithumbProject/Sources/Views/OrderBookTickerCell.swift
  BithumbProject/BithumbProject/Sources/Views/OrderBookTransactionCell.swift
  BithumbProject/BithumbProject/Sources/Views/OrderBookViewController.swift
  BithumbProject/BithumbProject/Sources/Views/TransactionCellViewController.swift
  BithumbProject/BithumbProject/Sources/Views/TransactionSmallCell.swift
  BithumbProject/BithumbProject/Sources/Views/TransactionViewController.swift
Labels: feat

#24 chore : 폴더정리
  BithumbProject/BithumbProject.xcodeproj/project.pbxproj
  BithumbProject/BithumbProject/Sources/Data/Data.swift
  BithumbProject/BithumbProject/Sources/Network/HTTPManager.swift
  BithumbProject/BithumbProject/Sources/Network/HTTPService.swift
  BithumbProject/BithumbProject/Sources/Network/WebSocketManager.swift
  BithumbProject/BithumbProject/Sources/Network/WebSocketService.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/Chart/ChartViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/Chart/SingleChartView.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/CoinDetailButtonBarPagerViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/CoinDetailViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/OrderBookCell.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/OrderBookTickerCell.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/OrderBookTransactionCell.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/OrderBookViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/TransactionSmallCell.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/Transaction/TransactionCellViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/Transaction/TransactionViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Main/ButtonBarCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/ButtonBarCollectionView.swift
  BithumbProject/BithumbProject/Sources/Views/Main/ButtonBarController.swift
  BithumbProject/BithumbProject/Sources/Views/Main/ChangeRateSettingHeaderView.swift
  BithumbProject/BithumbProject/Sources/Views/Main/ChangeRateSettingViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Main/CoinCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/CoinListViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Main/PeriodCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/StarButton.swift
  BithumbProject/BithumbProject/Sources/Views/Main/StarCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/TickerCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/TitleCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/TransactionCell.swift
Labels: refactor

#25 feat : OrderBookr ViewController 수정
  BithumbProject/BithumbProject.xcodeproj/project.pbxproj
  BithumbProject/BithumbProject/Sources/SupportingFiles/Extensions/String+Extension.swift
  BithumbProject/BithumbProject/Sources/ViewModels/OrderBookViewModel.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/OrderBookPriceCell.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/OrderBookQuantityCell.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/OrderBookTickerCell.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/OrderBookViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/Transaction/TransactionSingleCell.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/Transaction/TransactionViewController.swift
Labels: feat

#26 feat: SingleChartView에 RealTimeTicker 연동
  BithumbProject/BithumbProject/Sources/Application/SceneDelegate.swift
  BithumbProject/BithumbProject/Sources/Models/Candlestick.swift
  BithumbProject/BithumbProject/Sources/Models/Coin.swift
  BithumbProject/BithumbProject/Sources/Models/RealtimeTicker.swift
  BithumbProject/BithumbProject/Sources/Models/Ticker.swift
  BithumbProject/BithumbProject/Sources/Network/WebSocketManager.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Extensions/UInt64+Extension.swift
  BithumbProject/BithumbProject/Sources/ViewModels/ChartViewModel.swift
  BithumbProject/BithumbProject/Sources/ViewModels/CoinDetailViewModel.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/Chart/ChartViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/Chart/SingleChartView.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/CoinDetailButtonBarPagerViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/CoinDetailViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Main/CoinListViewController.swift
Labels: feat

#28 non-issue: Conflict 해결
  BithumbProject/BithumbProject.xcodeproj/project.pbxproj
  BithumbProject/BithumbProject/Sources/Application/CoinListService.swift
  BithumbProject/BithumbProject/Sources/Application/SceneDelegate.swift
  BithumbProject/BithumbProject/Sources/Models/ChangeRate.swift
  BithumbProject/BithumbProject/Sources/Models/ChangeRatePeriod.swift
  BithumbProject/BithumbProject/Sources/Models/Coin.swift
  BithumbProject/BithumbProject/Sources/Models/CoinListType.swift
  BithumbProject/BithumbProject/Sources/Models/RealtimeTicker.swift
  BithumbProject/BithumbProject/Sources/Models/Ticker.swift
  BithumbProject/BithumbProject/Sources/Models/TickerString.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Extensions/Double+Extension.swift
  BithumbProject/BithumbProject/Sources/ViewModels/CoinListViewModel.swift
  BithumbProject/BithumbProject/Sources/ViewModels/HoldingsViewModel.swift
  BithumbProject/BithumbProject/Sources/Views/Main/CustomView/ButtonBarCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/CustomView/ButtonBarCollectionView.swift
  BithumbProject/BithumbProject/Sources/Views/Main/CustomView/ButtonBarController.swift
  BithumbProject/BithumbProject/Sources/Views/Main/CustomView/MainTabBarController.swift
  BithumbProject/BithumbProject/Sources/Views/Main/CustomView/StarButton.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/ChangeRateCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/ChangeRateSettingHeaderView.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/ChangeRateSettingViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/CoinCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/CoinListViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/PeriodCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/StarCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/TickerCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/TitleCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/TransactionCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Holdings/HoldingsViewController.swift
Labels: non-issue

#29 feat : CoinDetail에 OrderBookViewController, TransactionViewController 연결
  BithumbProject/BithumbProject.xcodeproj/project.pbxproj
  BithumbProject/BithumbProject/Sources/SupportingFiles/Extensions/String+Extension.swift
  BithumbProject/BithumbProject/Sources/ViewModels/OrderBookViewModel.swift
  BithumbProject/BithumbProject/Sources/ViewModels/TransactionViewModel.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/CoinDetailButtonBarPagerViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/OrderBookViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/TransactionCellViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/Transaction/TransactionViewController.swift
Labels: feat

#30 feat : 호가창 quantityBar 추가
  BithumbProject/BithumbProject/Sources/SupportingFiles/Extensions/String+Extension.swift
  BithumbProject/BithumbProject/Sources/ViewModels/OrderBookViewModel.swift
  BithumbProject/BithumbProject/Sources/ViewModels/TransactionViewModel.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/OrderBookQuantityCell.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/OrderBookTickerCell.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/OrderBookViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/TransactionCellViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/Transaction/TransactionViewController.swift
Labels: feat

#32 feat: SingleViewChart에 RealmSwift 적용
  BithumbProject/BithumbProject.xcodeproj/project.pbxproj
  BithumbProject/BithumbProject/Sources/Data/BarChartObject.swift
  BithumbProject/BithumbProject/Sources/Data/BarObject.swift
  BithumbProject/BithumbProject/Sources/Data/CandlestickChartObject.swift
  BithumbProject/BithumbProject/Sources/Data/CandlestickObject.swift
  BithumbProject/BithumbProject/Sources/Data/Data.swift
  BithumbProject/BithumbProject/Sources/Data/RealmManager.swift
  BithumbProject/BithumbProject/Sources/Models/Candlestick.swift
  BithumbProject/BithumbProject/Sources/Models/IntString.swift
  BithumbProject/BithumbProject/Sources/Models/RealtimeTickType.swift
  BithumbProject/BithumbProject/Sources/Models/RealtimeTicker.swift
  BithumbProject/BithumbProject/Sources/Models/UpDown.swift
  BithumbProject/BithumbProject/Sources/Network/WebSocketManager.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Extensions/Date+Extenstion.swift
  BithumbProject/BithumbProject/Sources/ViewModels/ChartViewModel.swift
  BithumbProject/BithumbProject/Sources/ViewModels/CoinDetailViewModel.swift
  BithumbProject/BithumbProject/Sources/ViewModels/OrderBookViewModel.swift
  BithumbProject/BithumbProject/Sources/ViewModels/TransactionViewModel.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/Chart/ChartViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/Chart/SingleChartView.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/CoinDetailButtonBarPagerViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/CoinDetailViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Main/CustomView/StarButton.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/CoinListViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/StarCell.swift
  BithumbProject/Podfile
  BithumbProject/Podfile.lock
Labels: feat, refactor

#36 Feat: 로그인 및 보유자산 화면 구현 및 리팩토링
  BithumbProject/BithumbProject.xcodeproj/project.pbxproj
  BithumbProject/BithumbProject/Resources/Assets.xcassets/launchImage.imageset/Contents.json
  BithumbProject/BithumbProject/Resources/Assets.xcassets/launchImage.imageset/launchImage.png
  BithumbProject/BithumbProject/Resources/Base.lproj/LaunchScreen.storyboard
  BithumbProject/BithumbProject/Sources/Application/SceneDelegate.swift
  BithumbProject/BithumbProject/Sources/Data/CommonUserDefault.swift
  BithumbProject/BithumbProject/Sources/Data/DataRepositoryProtocol.swift
  BithumbProject/BithumbProject/Sources/Models/AssetsStatus.swift
  BithumbProject/BithumbProject/Sources/Models/Coin.swift
  BithumbProject/BithumbProject/Sources/Models/CoinListType.swift
  BithumbProject/BithumbProject/Sources/Models/Holdings.swift
  BithumbProject/BithumbProject/Sources/Models/RealtimeTicker.swift
  BithumbProject/BithumbProject/Sources/Models/SortedColumn.swift
  BithumbProject/BithumbProject/Sources/Models/TickerString.swift
  BithumbProject/BithumbProject/Sources/Models/User.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Constants/Constant.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Extensions/Double+Extension.swift
  BithumbProject/BithumbProject/Sources/ViewModels/CoinListViewModel.swift
  BithumbProject/BithumbProject/Sources/ViewModels/HoldingsViewModel.swift
  BithumbProject/BithumbProject/Sources/Views/Main/CustomView/ButtonBarCollectionView.swift
  BithumbProject/BithumbProject/Sources/Views/Main/CustomView/SignUpTextField.swift
  BithumbProject/BithumbProject/Sources/Views/Main/CustomView/StarButton.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/ChangeRateCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/CoinCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/CoinListViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/StarCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/TickerCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Exchange/TransactionCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Holdings/HoldingsHeaderView.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Holdings/HoldingsTableViewCell.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Holdings/HoldingsViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Main/Login/SignUpViewController.swift
  README.md
Labels: feat

#37 feat: RealmManager, RealmService 구현 및 적용
  BithumbProject/BithumbProject.xcodeproj/project.pbxproj
  BithumbProject/BithumbProject/Sources/Data/BarChartObject.swift
  BithumbProject/BithumbProject/Sources/Data/BarObject.swift
  BithumbProject/BithumbProject/Sources/Data/CandlestickObject.swift
  BithumbProject/BithumbProject/Sources/Data/RealmManager.swift
  BithumbProject/BithumbProject/Sources/Data/RealmService.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Extensions/Date+Extension.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Extensions/Date+Extenstion.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Extensions/UIVIewController+Extension.swift
  BithumbProject/BithumbProject/Sources/ViewModels/ChartViewModel.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/Chart/ChartViewController.swift
Labels: feat, refactor

#38 Refactor : 디자인 적용, 코드 정리, 호가창 이슈 수정
  BithumbProject/BithumbProject/Sources/Models/OrderBook.swift
  BithumbProject/BithumbProject/Sources/Models/Ticker.swift
  BithumbProject/BithumbProject/Sources/Models/TransactionHistory.swift
  BithumbProject/BithumbProject/Sources/SupportingFiles/Constants/Constant.swift
  BithumbProject/BithumbProject/Sources/ViewModels/OrderBookViewModel.swift
  BithumbProject/BithumbProject/Sources/ViewModels/TransactionViewModel.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/OrderBookQuantityCell.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/OrderBookViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/TransactionCellViewController.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/TransactionSmallCell.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/Transaction/TransactionSingleCell.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/Transaction/TransactionViewController.swift
Labels: feat, refactor

#39 chore : print 제거
  BithumbProject/BithumbProject/Sources/ViewModels/OrderBookViewModel.swift
  BithumbProject/BithumbProject/Sources/Views/Detail/OrderBook/OrderBookViewController.swift
Labels: non-issue

#42 refactor: 리드미 수정 및 Realm 관련 코드 수정
  BithumbProject/BithumbProject/Sources/Data/RealmManager.swift
  BithumbProject/BithumbProject/Sources/Data/RealmService.swift
  BithumbProject/BithumbProject/Sources/ViewModels/ChartViewModel.swift
  README.md
Labels: refactor
